#ifndef PROJECT_CUPSENSE_CONFIG_H
#define PROJECT_CUPSENSE_CONFIG_H

// Ultrasonic Sensor's
#define US_WATER_ECHO_PIN     42
#define US_WATER_TRIGGER_PIN  41
#define US_HEIGHT_ECHO_PIN    40
#define US_HEIGHT_TRIGGER_PIN 39

// Builtin RGB LED
#define ONBOARD_RGB_PIN 38

#define ONBOARD_RGB_BRIGHTNESS 10

// Servo
#define SERVO_PIN 15

#define SERVO_SPEED_STOP 1477
#define SERVO_SPEED_FORWARDS 1628
#define SERVO_SPEED_BACKWARDS 1317
#define COG_RADIUS_CM 0.68
#define FULL_ROTATION_TIME 0.76
#define MAX_SERVO_MOVEMENT_CM 10.00
#define MIN_SERVO_MOVEMENT_CM 0.00

// Touch
#define TOUCH_IRQ_PIN 4
#define TOUCH_DO_PIN  5
#define TOUCH_DIN_PIN 6
#define TOUCH_CS_PIN  7
#define TOUCH_CLK_PIN 8
// Screen
#define SCREEN_MISO_PIN   14
#define SCREEN_LED_PIN    45
#define SCREEN_SCK_PIN    13
#define SCREEN_MOSI_PIN   12
#define SCREEN_DC_PIN     11
#define SCREEN_RESET_PIN  10
#define SCREEN_CS_PIN      9

#define SCREEN_ROTATION 1
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define FONT_SIZE 2
#define TOUCH_PRESSURE_PRESSED 4150
#define TOUCH_DEBOUNCE_DELAY_MS 100

#define TOUCH_LEFT  3700
#define TOUCH_RIGHT  500
#define TOUCH_TOP   3350
#define TOUCH_BOTTOM 700

// Pumps
#define RELAY_0_PIN 48
#define RELAY_1_PIN 47
#define RELAY_2_PIN 21

#endif //PROJECT_CUPSENSE_CONFIG_H
