#ifndef PROJECT_CUPSENSE_CONFIG_H
#define PROJECT_CUPSENSE_CONFIG_H

#define DEBUGGING false

// Ultrasonic Sensor's
#define US_ECHO 6
#define US_TRIGGER 7

// Builtin RGB LED
#define ONBOARD_RGB 38
#define ONBOARD_RGB_BRIGHTNESS 10

// Servo
#define SERVO_PIN 17
#define SERVO_SPEED_STOP 1472 // 90°
#define SERVO_SPEED_FORWARDS 1628 // 105°
#define SERVO_SPEED_BACKWARDS 1317 // 75°
#define SERVO_DELAY 95
#define COG_RADIUS_CM 0.65
#define FULL_ROTATION_TIME 0.92
#define MAX_SERVO_MOVEMENT_CM 10.00
#define MIN_SERVO_MOVEMENT_CM 0.00

// Touch Screen

#endif //PROJECT_CUPSENSE_CONFIG_H
